### ISSUE TITLE
no USERS counted on GA, it only show the events?

### ISSUE THREAD

**Issue by eggsongod** [564398053/Qt-GoogleAnalytics4#1]
is that right?

在GA的报表中，用户显示都是0，但Events是有实时数据。请问是这样吗？

**Comment by 564398053** [comment]
后续我去检查一下代码是不是写错了，GA的实时数据显示没那么准确，要过几分钟才看的到。

**Comment by eggsongod** [comment]
> 后续我去检查一下代码是不是写错了，GA的实时数据显示没那么准确，要过几分钟才看的到。

我只有Events数据，用户数一直显示0，无论多久还是0，我一开始觉得是因为没有“Page_view”这个event的原因，然后我伪造了page_view event，并且按照page_view event的params传了page_location和page_title，但还是没有效果，后来甚至传了ga_session_id和ga_session_number，仍然只有events数据，用户数还是0

**Comment by eggsongod** [comment]
> > 后续我去检查一下代码是不是写错了，GA的实时数据显示没那么准确，要过几分钟才看的到。
> 
> 我只有Events数据，用户数一直显示0，无论多久还是0，我一开始觉得是因为没有“Page_view”这个event的原因，然后我伪造了page_view event，并且按照page_view event的params传了page_location和page_title，但还是没有效果，后来甚至传了ga_session_id和ga_session_number，仍然只有events数据，用户数还是0

根据这里的描述：
https://developers.google.com/analytics/devguides/collection/protocol/ga4/sending-events?client_type=gtag#optional_parameters_for_reports

void GAnalytics::sendEvent中的params中加入
`eventParams["engagement_time_msec"] = 100;
 eventParams["session_id"] = d->m_clientID;`
解决了

**Comment by 564398053** [comment]
感谢. 我会更新到项目中.

**Comment by 564398053** [comment]
> > > 后续我去检查一下代码是不是写错了，GA的实时数据显示没那么准确，要过几分钟才看的到。
> > 
> > 
> > 我只有Events数据，用户数一直显示0，无论多久还是0，我一开始觉得是因为没有“Page_view”这个event的原因，然后我伪造了page_view event，并且按照page_view event的params传了page_location和page_title，但还是没有效果，后来甚至传了ga_session_id和ga_session_number，仍然只有events数据，用户数还是0
> 
> 根据这里的描述： https://developers.google.com/analytics/devguides/collection/protocol/ga4/sending-events?client_type=gtag#optional_parameters_for_reports
> 
> void GAnalytics::sendEvent中的params中加入 `eventParams["engagement_time_msec"] = 100; eventParams["session_id"] = d->m_clientID;` 解决了

感谢. 我会更新到项目中.

**Comment by eggsongod** [comment]
> > > > 后续我去检查一下代码是不是写错了，GA的实时数据显示没那么准确，要过几分钟才看的到。
> > > 
> > > 
> > > 我只有Events数据，用户数一直显示0，无论多久还是0，我一开始觉得是因为没有“Page_view”这个event的原因，然后我伪造了page_view event，并且按照page_view event的params传了page_location和page_title，但还是没有效果，后来甚至传了ga_session_id和ga_session_number，仍然只有events数据，用户数还是0
> > 
> > 
> > 根据这里的描述： https://developers.google.com/analytics/devguides/collection/protocol/ga4/sending-events?client_type=gtag#optional_parameters_for_reports
> > void GAnalytics::sendEvent中的params中加入 `eventParams["engagement_time_msec"] = 100; eventParams["session_id"] = d->m_clientID;` 解决了
> 
> 感谢. 我会更新到项目中.

还有很多数据没有值，比如地理位置，语言等等，我暂时也没有找到对应的地方。另外session_id理论上不能用clientID，因为session_id按GA的设计，应该是不操作30分钟后就会变。我只是简单测试而已。

**Comment by 564398053** [comment]
session_id 参考文章 https://support.google.com/analytics/answer/9191807.
用clientID也没什么问题. 会话数在客户端程序中意义不是太大. 统计程序的打开次数可以单独发一个事件如"open_app"

**Comment by 564398053** [comment]
地理维度（例如，城市、区域）是根据流量的 IP 地址近似计算的。
语言的话，可以获取操作系统语言主动发一个事件。

**Comment by eggsongod** [comment]
> 地理维度（例如，城市、区域）是根据流量的 IP 地址近似计算的。 语言的话，可以获取操作系统语言主动发一个事件。

地理维度这个问题我也以为是GA自动根据流量IP计算，但实际上，GA的后台报表并没有这个数据。语言的话，我也获取到了，只是不知道发动那个事件让GA认可。后来只能写一个自定义的事件。但这样的话，就不能作为GA原生的dim来操作了

**Comment by 564398053** [comment]
地理位置信息只能通过自动收集功能从 gtag、Google 跟踪代码管理器或 Google Analytics for Firebase 获取。

解读：
也就是通过http的mp协议是无法获取到地理位置信息的。

参考文档 `https://developers.google.cn/analytics/devguides/collection/protocol/ga4?hl=zh-cn`
